<?php

namespace app\modules\parameter\models;

use Yii;
use app\modules\file\models\File;
use yii\db\ActiveRecord;
use yii\web\UploadedFile;

/**
 * This is the model class for table "{{%parameter}}".
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $code
 * @property string $name
 * @property string $data
 * @property integer $active
 * @property integer $type
 * @property integer $position
 * @property string $update
 *
 */
class Parameter extends ActiveRecord
{
    public $file;

    const PARAMETER_CATEGORIES = [
        0 => 'Основные настройки',
    ];

    const PARAMETER_TYPES = [
        0 => 'Строка',
        1 => 'Текст',
        2 => 'Чекбокс',
        3 => 'Файл',
    ];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%parameter}}';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'code'], 'required'],
            [['category_id', 'active', 'type','position'], 'integer'],
            [['name', 'code'], 'string', 'max' => 255],
            [['data'], 'string'],
            [['update'], 'safe'],
            [['file'], 'file', 'skipOnEmpty' => true],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'category_id' => 'Категория',
            'code' => 'Псевдоним',
            'name' => 'Название',
            'active' => 'Активность',
            'data' => 'Значение',
            'type' => 'Тип',
        ];
    }

    /**
     * @inheritdoc
     */
    public function getCategory()
    {
        return self::PARAMETER_CATEGORIES[$this->category_id];
    }

    public function beforeSave($insert)
    {
        $this->update = date('Y-m-d H:i:s');
        if (empty($this->position)) {
            $position = self::find()->select('position')->max('position');
            $this->position = 1 + $position;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
